// Copyright 2023 Adrian Pfaff

#pragma once

#include "CoreMinimal.h"

UENUM(BlueprintType)
enum class ETrafficSignVariability : uint8
{
	VARIABILITY_UNKNOWN				UMETA(Hidden, DisplayName="Unknown", Tooltip="Variability type of sign is unknown (must not be used in ground truth)."),
	VARIABILITY_OTHER				UMETA(DisplayName="Other", Tooltip="Other (unspecified but known) variability."),
	VARIABILITY_FIXED				UMETA(DisplayName="Fixed", Tooltip="Sign that can change neither semantically nor positionally, e.g. a fixed, immutable, non-temporary traffic sign."),
	VARIABILITY_VARIABLE			UMETA(Hidden, DisplayName="Variable", Tooltip="Sign that can change semantically and/or positionally, i.e. it is left unspecified in which way the sign may change. Note This value represents a legacy definition. If possible, please use the more specific values below to indicate the exact nature of variability."),
	VARIABILITY_MOVABLE				UMETA(DisplayName="Movable", Tooltip="Sign that can change positionally but not semantically, e.g. a temporary, immutable traffic sign at construction site."),
	VARIABILITY_MUTABLE				UMETA(DisplayName="Mutable", Tooltip="Sign that can change semantically but not positionally, e.g. a digital traffic sign on traffic sign gantry, or an analog prism sign."),
	VARIABILITY_MOVABLE_AND_MUTABLE UMETA(DisplayName="Movable and Mutable", Tooltip="Sign that can change both semantically and positionally, e.g. a temporary, digital traffic sign at a construction site, or a digital traffic sign attached to a road works vehicle.")
};

UENUM(BlueprintType)
enum class ESignDirectionScope : uint8
{
	DIRECTION_SCOPE_UNKNOWN			UMETA(Hidden, DisplayName="Unknown", Tooltip="Direction of the sign's scope is unknown (must not be used in ground truth)."),
	DIRECTION_SCOPE_OTHER			UMETA(DisplayName="Other", Tooltip="Other (unspecified but known) direction of the sign's scope."),
	DIRECTION_SCOPE_NO_DIRECTION	UMETA(DisplayName="No Direction", Tooltip="Direction of the sign's scope is not specified."),
	DIRECTION_SCOPE_LEFT			UMETA(DisplayName="Left", Tooltip="Direction of the sign's scope for its viewer is left."),
	DIRECTION_SCOPE_RIGHT			UMETA(DisplayName="Right", Tooltip="Direction of the sign's scope for its viewer is right."),
	DIRECTION_SCOPE_LEFT_RIGHT		UMETA(DisplayName="Left Right", Tooltip="Direction of the sign's scope for its viewer is to both sides.")
};

UENUM(BlueprintType)
enum class ETrafficSignUnit : uint8
{
	UNIT_UNKNOWN			UMETA(Hidden, DisplayName="Unknown", Tooltip="Unit of the sign's value is unknown (must not be used in ground truth)."),
	UNIT_OTHER				UMETA(DisplayName="Other", Tooltip="Other (unspecified but known) unit of the sign's value."),
	UNIT_NO_UNIT			UMETA(DisplayName="No Unit", Tooltip="Value without unit."),
	UNIT_KILOMETER_PER_HOUR	UMETA(DisplayName="Kilometer per hour", Tooltip="Velocity. Kilometers per hour. Unit: km/h "),
	UNIT_MILE_PER_HOUR		UMETA(DisplayName="Mile per hour", Tooltip="Velocity. Miles per hour. Unit: mph"),
	UNIT_METER				UMETA(DisplayName="Meter", Tooltip="Length. Meter. Unit: m"),
	UNIT_KILOMETER			UMETA(DisplayName="Kilometer", Tooltip="Length. Kilometer. Unit: km"),
	UNIT_FEET				UMETA(DisplayName="Feet", Tooltip="Length. Unit: ft"),
	UNIT_MILE				UMETA(DisplayName="Mile", Tooltip="Length. Mile. Unit: mile"),
	UNIT_METRIC_TON			UMETA(DisplayName="Metric Ton", Tooltip="Weight. Ton. Unit: t"),
	UNIT_LONG_TON			UMETA(DisplayName="Long Ton", Tooltip="Weight. Long ton UK 1,016.047 kg. Unit: tn. l. "),
	UNIT_SHORT_TON			UMETA(DisplayName="Short Ton", Tooltip="Weight. Short ton USA 907.1847 kg. Unit: tn. sh."),
	UNIT_HOUR				UMETA(DisplayName="Hour", Tooltip="Time of day. Hours since midnight. Starting with 0. Unit: h"),
	UNIT_MINUTES			UMETA(DisplayName="Minutes", Tooltip="Time of day. Minutes since last hour. Starting with 0. Unit: min"),
	UNIT_DAY_OF_MONTH		UMETA(DisplayName="Day of Month", Tooltip="Day of the month. Starting with 1."),
	UNIT_DAY				UMETA(DisplayName="Day", Tooltip="Day of the week. Days since Monday. Monday = 0; Tuesday = 1; .."),
	UNIT_PERCENTAGE			UMETA(DisplayName="Percentage", Tooltip="Percentage. Value. Unit: %"),
	UNIT_DURATION_DAY		UMETA(DisplayName="Duration Day", Tooltip="Duration in days. Unit: day"),
	UNIT_DURATION_HOUR		UMETA(DisplayName="Duration Hour", Tooltip="Duration in hours. Unit: h "),
	UNIT_DURATION_MINUTE	UMETA(DisplayName="Duration Minute", Tooltip="Duration in minutes. Unit: min")
};

UENUM(BlueprintType)
enum class EMainSignType : uint8
{
	TYPE_UNKNOWN = 0										UMETA(Hidden, DisplayName="Unknown", Tooltip="Type of traffic sign is unknown (must not be used in ground truth)."),
  	TYPE_OTHER = 1											UMETA(DisplayName="Other", Tooltip="Other (unspecified but known) type of traffic sign."),
	TYPE_DANGER_SPOT = 2									UMETA(DisplayName="Danger Spot", Tooltip="Warning: Danger sign. StVO 101"),
	TYPE_ZEBRA_CROSSING = 87								UMETA(DisplayName="Zebra Crossing", Tooltip="Warning: Zebra crossing. StVO 101-11 Set vertically_mirrored to false. StVO 101-21 	Set vertically_mirrored to true. StVO 350-10 	Set vertically_mirrored to false. StVO 350-20 Set vertically_mirrored to true. As symbolic road marking RoadMarking::Classification::TYPE_SYMBOLIC_TRAFFIC_SIGN. StVO 293 "),
	TYPE_FLIGHT = 110										UMETA(DisplayName="Flight", Tooltip="Warning: Low-flying aircraft or sudden aircraft noise.StVO 101-10 Set vertically_mirrored to false.StVO 101-20 Set vertically_mirrored to true. "),
	TYPE_CATTLE = 200										UMETA(DisplayName="Cattle", Tooltip="Warning: Cattles crossing. StVO 101-12 Set vertically_mirrored to false. StVO 101-22 	Set vertically_mirrored to true. "),
	TYPE_HORSE_RIDERS = 197									UMETA(DisplayName="Horse Riders", Tooltip="Warning: Horse riders. StVO 101-13 Set vertically_mirrored to false.StVO 101-23 Set vertically_mirrored to true."),
	TYPE_AMPHIBIANS = 188									UMETA(DisplayName="Amphibians", Tooltip="Warning: Amphibian migration. StVO 101-14 	Set vertically_mirrored to false. StVO 101-24 	Set vertically_mirrored to true. "),
  	TYPE_FALLING_ROCKS = 96									UMETA(DisplayName="Falling Rocks", Tooltip="Warning: Falling rocks. StVO 101-15 Set vertically_mirrored to false. StVO 101-25 	Set vertically_mirrored to true."),
	TYPE_SNOW_OR_ICE = 94									UMETA(DisplayName="Snow or Ice", Tooltip="Warning: Risk of snow or ice. StVO 101-51 "),
	TYPE_LOOSE_GRAVEL = 97									UMETA(DisplayName="Loose Gravel", Tooltip="Warning: Crushed stones. StVO 101-52"),
	TYPE_WATERSIDE = 102									UMETA(DisplayName="Waterside", Tooltip="Warning: Waterside. StVO 101-53"),
	TYPE_CLEARANCE = 210									UMETA(DisplayName="Clearance", Tooltip="Warning: Not enough clearance. StVO 101-54"),
	TYPE_MOVABLE_BRIDGE = 101								UMETA(DisplayName="Movable Bridge", Tooltip="Warning: Movable bridge. StVO 101-55"),
	TYPE_RIGHT_BEFORE_LEFT_NEXT_INTERSECTION = 3			UMETA(DisplayName="Right before Left at next Intersection", Tooltip="Warning: \"Right before left\" rule at the next intersection. StVO 102"),
	TYPE_TURN_LEFT = 4										UMETA(DisplayName="Turn Left", Tooltip="Warning: Sign for a left turn. StVO 103-10 Right: TYPE_TURN_RIGHT"),
	TYPE_TURN_RIGHT = 5										UMETA(DisplayName="Turn Right", Tooltip="Warning: Sign for a right turn. StVO 103-20 Left: TYPE_TURN_LEFT"),
	TYPE_DOUBLE_TURN_LEFT = 6								UMETA(DisplayName="Double Turn Left", Tooltip="Warning: Sign for a double turn (first left turn). StVO 105-10 Right: TYPE_DOUBLE_TURN_RIGHT"),
	TYPE_DOUBLE_TURN_RIGHT = 7								UMETA(DisplayName="Double Turn Right", Tooltip="Warning: Sign for a double turn (first right turn). StVO 105-20 Left: TYPE_DOUBLE_TURN_LEFT"),
	TYPE_HILL_DOWNWARDS = 8									UMETA(DisplayName="Hill Downwards", Tooltip="Warning: Steep hill downwards. StVO 108 	Use TrafficSignValue::value and TrafficSignValue::value_unit to indicate slope."),
	TYPE_HILL_UPWARDS = 9									UMETA(DisplayName="Hill Upwards", Tooltip="Warning: Steep hill upwards. StVO 110 	Use TrafficSignValue::value and TrafficSignValue::value_unit to indicate slope "),
	TYPE_UNEVEN_ROAD = 93									UMETA(DisplayName="Uneven Road", Tooltip="Warning: Uneven road. StVO 112"),
	TYPE_ROAD_SLIPPERY_WET_OR_DIRTY = 95					UMETA(DisplayName="Road Slippery", Tooltip="Warning: Road slippery when wet or dirty. StVO 114"),
	TYPE_SIDE_WINDS = 98									UMETA(DisplayName="Side Winds", Tooltip="Warning: Side winds. StVO 117-10 	Set vertically_mirrored to false. StVO 117-20 	Set vertically_mirrored to true."),
	TYPE_ROAD_NARROWING = 10								UMETA(DisplayName="Road Narrowing", Tooltip="Warning: Road narrowing. StVO 120"),
	TYPE_ROAD_NARROWING_RIGHT = 12							UMETA(DisplayName="Road Narrowing Right", Tooltip="Warning: Road narrowing on the right. StVO 121-10"),
	TYPE_ROAD_NARROWING_LEFT = 11							UMETA(DisplayName="Road Narrowing Left", Tooltip="Warning: Road narrowing on the left. StVO 121-20"),
	TYPE_ROAD_WORKS = 13									UMETA(DisplayName="Road Works", Tooltip="Warning: Road works sign. StVO 123"),
	TYPE_TRAFFIC_QUEUES = 100								UMETA(DisplayName="Traffic Queues", Tooltip="Warning: Traffic queues likely. StVO 124"),
	TYPE_TWO_WAY_TRAFFIC = 14								UMETA(DisplayName="Two Way Traffic", Tooltip="Warning: Two-way-traffic (after one-way lane). StVO 125"),
	TYPE_ATTENTION_TRAFFIC_LIGHT = 15						UMETA(DisplayName="Attention Traffic Light", Tooltip="Warning: Traffic light ahead sign. StVO 131"),
	TYPE_PEDESTRIANS = 103									UMETA(DisplayName="Pedestrians", Tooltip="Warning: Pedestrians. StVO 133-10 Set vertically_mirrored to false. StVO 133-20 Set vertically_mirrored to true."),
	TYPE_CHILDREN_CROSSING = 106							UMETA(DisplayName="Children Crossing", Tooltip="Warning: Children crossing. StVO 136-10 Set vertically_mirrored to false. StVO 136-20 Set vertically_mirrored to true."),
	TYPE_CYCLE_ROUTE = 107									UMETA(DisplayName="Cycle Route", Tooltip="Warning: Pedal cycle route crossing or joining road sign. StVO 138-10 Set vertically_mirrored to false. StVO 138-20 Set vertically_mirrored to true."),
	TYPE_DEER_CROSSING = 109								UMETA(DisplayName="Deer Crossing", Tooltip="Warning: Deer crossing. StVO 142-10 Set vertically_mirrored to false. StVO 142-20 Set vertically_mirrored to true"),
	TYPE_UNGATED_LEVEL_CROSSING = 144						UMETA(DisplayName="Ungated Level Crossing", Tooltip="Warning: Level crossing without barrier or gate. StVO 151"),
	TYPE_LEVEL_CROSSING_MARKER = 112						UMETA(DisplayName="Level Crossing Marker", Tooltip="Level crossing marker. (StVO 156 - Countdown marker indicating that level crossing are 2 main signs TYPE_UNGATED_LEVEL_CROSSING and TYPE_LEVEL_CROSSING_MARKER.) StVO 157-10 	StVO 159-10 	StVO 161-10 	(StVO 156-10) 	(StVO 156-11) StVO 157-20 	StVO 159-20 	StVO 162-20 	(StVO 156-20) 	(StVO 156-21) Variants (here X is any of 157, 159 or 162): StVO X-10 	Set vertically_mirrored to false. StVO X-11 	Set vertically_mirrored to false. Additionally, use TrafficSignValue::value and TrafficSignValue::value_unit to indicate the remaining distance or the number of displayed red stripes. In the second case, set TrafficSignValue::value_unit to TrafficSignValue::UNIT_NO_UNIT. StVO X-20 	Set vertically_mirrored to true. StVO X-21 	Set vertically_mirrored to true. Additionally, use TrafficSignValue::value and TrafficSignValue::value_unit to indicate the remaining distance or the number of displayed red stripes. In the second case, set TrafficSignValue::value_unit to TrafficSignValue::UNIT_NO_UNIT. "),
	TYPE_RAILWAY_TRAFFIC_PRIORITY = 135						UMETA(DisplayName="Railway Traffic Priority", Tooltip="St.Andrew's cross, railway traffic has priority. StVO 201-50 StVO 201-52 with lightning bolt indicating voltage-carrying overhead line."),
	TYPE_GIVE_WAY = 16										UMETA(DisplayName="Give Way", Tooltip="Give way. StVO 205 As symbolic road marking RoadMarking::Classification::TYPE_SYMBOLIC_TRAFFIC_SIGN. StVO 341"),
	TYPE_STOP = 17											UMETA(DisplayName="Stop", Tooltip="Stop sign. StVO 206 As symbolic road marking RoadMarking::Classification::TYPE_SYMBOLIC_TRAFFIC_SIGN. StVO 294"),
	TYPE_PRIORITY_TO_OPPOSITE_DIRECTION = 18				UMETA(DisplayName="Priority to Opposite Direction", Tooltip="Priority must be given to vehicles from the opposite direction. StVO 208 See also: TYPE_PRIORITY_OVER_OPPOSITE_DIRECTION."),
	TYPE_PRIORITY_TO_OPPOSITE_DIRECTION_UPSIDE_DOWN = 19	UMETA(DisplayName="Priority to Opposite Direction upside down", Tooltip="Priority must be given to vehicles from the opposite direction. StVO 208, upside down. See also: TYPE_PRIORITY_TO_OPPOSITE_DIRECTION."),
	TYPE_PRESCRIBED_LEFT_TURN = 20							UMETA(DisplayName="Prescribed Left Turn", Tooltip="Prescribed left turn. StVO 209-10 Right: TYPE_PRESCRIBED_RIGHT_TURN As symbolic road marking RoadMarking::Classification::TYPE_SYMBOLIC_TRAFFIC_SIGN (StVO 297)."),
	TYPE_PRESCRIBED_RIGHT_TURN = 21							UMETA(DisplayName="Prescribed Right Turn", Tooltip="Prescribed right turn. StVO 209-20 Left: TYPE_PRESCRIBED_LEFT_TURN As symbolic road marking RoadMarking::Classification::TYPE_SYMBOLIC_TRAFFIC_SIGN (StVO 297)."),
	TYPE_PRESCRIBED_STRAIGHT = 22							UMETA(DisplayName="Prescribed Straight", Tooltip="Prescribed driving straight. StVO 209-30 As symbolic road marking RoadMarking::Classification::TYPE_SYMBOLIC_TRAFFIC_SIGN (StVO 297)."),
	TYPE_PRESCRIBED_RIGHT_WAY = 24							UMETA(DisplayName="Prescribed Right Way", Tooltip="Prescribed right way. StVO 211 Left: TYPE_PRESCRIBED_LEFT_WAY"),
	TYPE_PRESCRIBED_LEFT_WAY = 23							UMETA(DisplayName="Prescribed Left Way", Tooltip="Prescribed left way. StVO 211-10 Right: TYPE_PRESCRIBED_RIGHT_WAY"),
	TYPE_PRESCRIBED_RIGHT_TURN_AND_STRAIGHT = 26			UMETA(DisplayName="Prescribed Right Turn and Straight", Tooltip="Prescribed right turn and driving straight. StVO 214 Left: TYPE_PRESCRIBED_LEFT_TURN_AND_STRAIGHT As symbolic road marking RoadMarking::Classification::TYPE_SYMBOLIC_TRAFFIC_SIGN (StVO 297)."),
	TYPE_PRESCRIBED_LEFT_TURN_AND_STRAIGHT = 25				UMETA(DisplayName="Prescribed Left Turn and Straight", Tooltip="Prescribed left turn and driving straight. StVO 214-10 Right: TYPE_PRESCRIBED_RIGHT_TURN_AND_STRAIGHT As symbolic road marking RoadMarking::Classification::TYPE_SYMBOLIC_TRAFFIC_SIGN (StVO 297)."),
	TYPE_PRESCRIBED_LEFT_TURN_AND_RIGHT_TURN = 27			UMETA(DisplayName="Prescribed Left Turn and Right Turn", Tooltip="Prescribed left and right turn. StVO 214-30 As symbolic road marking RoadMarking::Classification::TYPE_SYMBOLIC_TRAFFIC_SIGN (StVO 297)."),
	TYPE_PRESCRIBED_LEFT_TURN_RIGHT_TURN_AND_STRAIGHT = 28	UMETA(DisplayName="Prescribed Left Turn, Right Turn and Straight", Tooltip="Prescribed left turn, right turn and driving straight (required for logical signs as road marking). As symbolic road marking RoadMarking::Classification::TYPE_SYMBOLIC_TRAFFIC_SIGN (StVO 297)."),
	TYPE_ROUNDABOUT = 29									UMETA(DisplayName="Roundabout", Tooltip="Roundabout. StVO 215 Note The direction of driving (clockwise, counterclockwise) is country-specific."),
	TYPE_ONEWAY_LEFT = 30									UMETA(DisplayName="Oneway Left", Tooltip="One-way road to the left. StVO 220-10 Right: TYPE_ONEWAY_RIGHT"),
	TYPE_ONEWAY_RIGHT = 31									UMETA(DisplayName="Oneway Right", Tooltip="One-way road to the right. StVO 220-20 Left: TYPE_ONEWAY_LEFT"),
	TYPE_PASS_LEFT = 32										UMETA(DisplayName="Pass Left", Tooltip="Drive past on the left side. StVO 222-10 Right: TYPE_PASS_RIGHT"),
	TYPE_PASS_RIGHT = 33									UMETA(DisplayName="Pass Right", Tooltip="Drive past on the right side. StVO 222 Left: TYPE_PASS_LEFT"),
	TYPE_SIDE_LANE_OPEN_FOR_TRAFFIC = 128					UMETA(DisplayName="Side Lane open for Traffic", Tooltip="Drive along side lanes. StVO 223.1-50 Drive along side lanes, 2 lanes and side lane. StVO 223.1-51 Drive along side lanes, 3 lanes and side lane. StVO 223.1-52 Drive along side lanes, 4 lanes and side lane."),
	TYPE_SIDE_LANE_CLOSED_FOR_TRAFFIC = 129					UMETA(DisplayName="Side Lane closed for Traffic", Tooltip="Do not drive on the side lane. StVO 223.2-50 Do not drive on the side lane, 2 lanes and side lane. StVO 223.2-51 Do not drive on the side lane, 3 lanes and side lane. StVO 223.2-52 Do not drive on the side lane, 4 lanes and side lane."),
	TYPE_SIDE_LANE_CLOSING_FOR_TRAFFIC = 130				UMETA(DisplayName="Side Lane closing for Traffic", Tooltip="Side lane closing. StVO 223.3-50 Side lane closing, 2 lanes and side lane. StVO 223.3-51 Side lane closing, 3 lanes and side lane. StVO 223.3-52 Side lane closing, 4 lanes and side lane."),
	TYPE_BUS_STOP = 137										UMETA(DisplayName="Bus Stop", Tooltip="Bus stop or tramway stop. StVO 224"),
	TYPE_TAXI_STAND = 138									UMETA(DisplayName="Taxi Stand", Tooltip="Taxi rank. StVO 229 Set Classification::direction_scope to DIRECTION_SCOPE_NO_DIRECTION StVO 229-10  StVO 229-21 Set Classification::direction_scope to DIRECTION_SCOPE_LEFT StVO 229-11 StVO 229-20 Set Classification::direction_scope to DIRECTION_SCOPE_RIGHT StVO 229-30 StVO 229-31 Set Classification::direction_scope to DIRECTION_SCOPE_LEFT_RIGHT"),
	TYPE_BICYCLES_ONLY = 145								UMETA(DisplayName="Bicycles only", Tooltip="Route for bicycles only. StVO 237"),
	TYPE_HORSE_RIDERS_ONLY = 146							UMETA(DisplayName="Horse Riders only", Tooltip="Route for horse riders only. StVO 238"),
	TYPE_PEDESTRIANS_ONLY = 147								UMETA(DisplayName="Pedestrians only", Tooltip="Route for pedestrians only. StVO 239"),
	TYPE_BICYCLES_PEDESTRIANS_SHARED_ONLY = 148				UMETA(DisplayName="Bicycles and Pedestrians shared", Tooltip="Unsegregated route for use by bicycles and pedestrians only. StVO 240"),
	TYPE_BICYCLES_PEDESTRIANS_SEPARATED_LEFT_ONLY = 149		UMETA(DisplayName="Bicycles and Pedestrians separated (Left)", Tooltip="Segregated route for use by bicycles and pedestrians only, bicycles on the left. StVO 241-30 Right: TYPE_BICYCLES_PEDESTRIANS_SEPARATED_RIGHT_ONLY"),
	TYPE_BICYCLES_PEDESTRIANS_SEPARATED_RIGHT_ONLY = 150	UMETA(DisplayName="Bicycles and Pedestrians separated (Right)", Tooltip="Segregated route for use by bicycles and pedestrians only, bicycles on the right. StVO 241-31 Left: TYPE_BICYCLES_PEDESTRIANS_SEPARATED_LEFT_ONLY"),
	TYPE_PEDESTRIAN_ZONE_BEGIN = 151						UMETA(DisplayName="Pedestrian Zone begin", Tooltip="Beginning of the pedestrian zone. StVO 242.1"),
	TYPE_PEDESTRIAN_ZONE_END = 152							UMETA(DisplayName="Pedestrian Zone end", Tooltip="End of the pedestrian zone. StVO 242.2"),
	TYPE_BICYCLE_ROAD_BEGIN = 153							UMETA(DisplayName="Bicycle Road begin", Tooltip="Beginning of bicycle road.S tVO 244.1"),
	TYPE_BICYCLE_ROAD_END = 154								UMETA(DisplayName="Bicycle Road end", Tooltip="End of bicycle road. StVO 244.2"),
	TYPE_BUS_LANE = 34										UMETA(DisplayName="Bus Lane", Tooltip="Lane for buses. StVO 245"),
	TYPE_BUS_LANE_BEGIN = 35								UMETA(DisplayName="Bus Lane begin", Tooltip="Bus only lane begin. End: TYPE_BUS_LANE_END"),
	TYPE_BUS_LANE_END = 36									UMETA(DisplayName="Bus Lane end", Tooltip="Bus only lane end. Begin: TYPE_BUS_LANE_BEGIN"),
	TYPE_ALL_PROHIBITED = 37								UMETA(DisplayName="All Prohibited", Tooltip="Entry prohibited for all types of vehicles. StVO 250"),
	TYPE_MOTORIZED_MULTITRACK_PROHIBITED = 38				UMETA(DisplayName="Motorized Multitrack Prohibited", Tooltip="Entry prohibited for cars, trucks, and other motorized multi-track vehicles. StVO 251"),
	TYPE_TRUCKS_PROHIBITED = 39								UMETA(DisplayName="Trucks prohibited", Tooltip="Entry prohibited for trucks. StVO 253 Note In the German StVO, trucks are defined as motorized vehicles that are heavier than 3.5 t."),
	TYPE_BICYCLES_PROHIBITED = 40							UMETA(DisplayName="Bicycles prohibited", Tooltip="Entry prohibited for bicycles. StVO 254"),
	TYPE_MOTORCYCLES_PROHIBITED = 41						UMETA(DisplayName="Motorcycles prohibited", Tooltip="Entry prohibited for motorcycles. StVO 255"),
	TYPE_MOPEDS_PROHIBITED = 155							UMETA(DisplayName="Mopeds prohibited", Tooltip="Entry prohibited for mopeds. StVO 257-50"),
	TYPE_HORSE_RIDERS_PROHIBITED = 156						UMETA(DisplayName="Horse Riders prohibited", Tooltip="Entry prohibited for horse riders. StVO 257-51"),
	TYPE_HORSE_CARRIAGES_PROHIBITED = 157					UMETA(DisplayName="Horse Carriages prohibited", Tooltip="Entry prohibited for horse carriages. StVO 257-52"),
	TYPE_CATTLE_PROHIBITED = 158							UMETA(DisplayName="Cattle prohibited", Tooltip="Entry prohibited for cattles. StVO 257-53"),
	TYPE_BUSES_PROHIBITED = 159								UMETA(DisplayName="Buses prohibited", Tooltip="Entry prohibited for buses. StVO 257-54"),
	TYPE_CARS_PROHIBITED = 160								UMETA(DisplayName="Cars prohibited", Tooltip="Entry prohibited for passenger cars. StVO 257-55"),
	TYPE_CARS_TRAILERS_PROHIBITED = 161						UMETA(DisplayName="Cars with Trailers prohibited", Tooltip="Entry prohibited for passenger cars with trailers. StVO 257-56"),
	TYPE_TRUCKS_TRAILERS_PROHIBITED = 162					UMETA(DisplayName="Trucks with Trailers prohibited", Tooltip="Entry prohibited for trucks with trailers. StVO 257-57"),
	TYPE_TRACTORS_PROHIBITED = 163							UMETA(DisplayName="Tractors prohibited", Tooltip="Entry prohibited for tractors. StVO 257-58 Note In the German StVO, tractors are defined as motorized vehicles that are not allowed to, or cannot, drive faster than 25 km/h."),
	TYPE_PEDESTRIANS_PROHIBITED = 42						UMETA(DisplayName="Pedestrians prohibited", Tooltip="Entry prohibited for pedestrians. StVO 259"),
	TYPE_MOTOR_VEHICLES_PROHIBITED = 43						UMETA(DisplayName="Motor vehicles prohibited", Tooltip="Entry prohibited for all motor vehicles. StVO 260"),
	TYPE_HAZARDOUS_GOODS_VEHICLES_PROHIBITED = 164			UMETA(DisplayName="Hazardous Goods Vehicles prohibited", Tooltip="Entry prohibited for marked vehicles transporting hazardous goods. StVO 261"),
	TYPE_OVER_WEIGHT_VEHICLES_PROHIBITED = 165				UMETA(DisplayName="Over weight Vehicles prohibited", Tooltip="Weight limit (entry prohibited for vehicles over maximum gross weight shown). StVO 262 Use TrafficSignValue::value and TrafficSignValue::value_unit to set the limit."),
	TYPE_VEHICLES_AXLE_OVER_WEIGHT_PROHIBITED = 166			UMETA(DisplayName="Vehicles axle over weight prohibited", Tooltip="Axle weight limit (entry prohibited for vehicles over weight on axle shown). StVO 263 Use TrafficSignValue::value and TrafficSignValue::value_unit to set the limit."),
	TYPE_VEHICLES_EXCESS_WIDTH_PROHIBITED = 167				UMETA(DisplayName="Vehicles excess width prohibited", Tooltip="Horizontal clearance (entry prohibited for vehicles wider than the width shown). StVO 264 Use TrafficSignValue::value and TrafficSignValue::value_unit to set the limit."),
	TYPE_VEHICLES_EXCESS_HEIGHT_PROHIBITED = 168			UMETA(DisplayName="Vehicles excess height prohibited", Tooltip="Vertical clearance (entry prohibited for vehicles higher than the height shown). StVO 265 Use TrafficSignValue::value and TrafficSignValue::value_unit to set the limit."),
	TYPE_VEHICLES_EXCESS_LENGTH_PROHIBITED = 169			UMETA(DisplayName="Vehicles escess length prohibited", Tooltip="Length restriction (entry prohibited for vehicles or combinations of vehicles longer than the length shown). StVO 266 Use TrafficSignValue::value and TrafficSignValue::value_unit to set the limit."),
	TYPE_DO_NOT_ENTER = 44									UMETA(DisplayName="Do not enter", Tooltip="Entry not allowed. One-way road. StVO 267"),
	TYPE_SNOW_CHAINS_REQUIRED = 170							UMETA(DisplayName="Snow chains required", Tooltip="Snow chains required. StVO 268"),
	TYPE_WATER_POLLUTANT_VEHICLES_PROHIBITED = 171			UMETA(DisplayName="Water pollutant Vehicles prohibited", Tooltip="Entry prohibited for vehicles carrying water pollutants. StVO 269"),
	TYPE_ENVIRONMENTAL_ZONE_BEGIN = 45						UMETA(DisplayName="Environmental Zone begin", Tooltip="Start of area without traffic to reduce harmful air pollution. StVO 270.1 End: TYPE_ENVIRONMENTAL_ZONE_END"),
	TYPE_ENVIRONMENTAL_ZONE_END = 46						UMETA(DisplayName="Environmental Zone end", Tooltip="End of area without traffic to reduce harmful air pollution. StVO 270.2 Begin: TYPE_ENVIRONMENTAL_ZONE_BEGIN"),
	TYPE_NO_U_TURN_LEFT = 47								UMETA(DisplayName="No U Turn left", Tooltip="No U turn left. StVO 272 Right: TYPE_NO_U_TURN_RIGHT"),
	TYPE_NO_U_TURN_RIGHT = 48								UMETA(DisplayName="No U Turn right", Tooltip="No U turn right. Note This type is to be applied in left-driving countries. Left: TYPE_NO_U_TURN_LEFT"),
	TYPE_PRESCRIBED_U_TURN_LEFT = 49						UMETA(DisplayName="Prescribed U Turn left", Tooltip="Prescribed U turn left. Right: TYPE_PRESCRIBED_U_TURN_RIGHT"),
	TYPE_PRESCRIBED_U_TURN_RIGHT = 50						UMETA(DisplayName="Prescribed U Turn right", Tooltip="Prescribed U turn right. Note This type is to be applied in left-driving countries. Left: TYPE_PRESCRIBED_U_TURN_LEFT"),
	TYPE_MINIMUM_DISTANCE_FOR_TRUCKS = 51					UMETA(DisplayName="Minimum Distance for Trucks", Tooltip="Minimum safety distance for trucks. StVO 273 Use TrafficSignValue::value and TrafficSignValue::value_unit to set the limit."),
	TYPE_SPEED_LIMIT_BEGIN = 52								UMETA(DisplayName="Speed Limit Begin", Tooltip="Start of speed limit. StVO 274 Use TrafficSignValue::value and TrafficSignValue::value_unit to set the limit. End: TYPE_SPEED_LIMIT_END"),
	TYPE_SPEED_LIMIT_ZONE_BEGIN = 53						UMETA(DisplayName="Speed Limit Zone begin", Tooltip="Start of zone with speed limit. StVO 274.1 Use TrafficSignValue::value and TrafficSignValue::value_unit to set the limit. End: TYPE_SPEED_LIMIT_ZONE_END"),
	TYPE_SPEED_LIMIT_ZONE_END = 54							UMETA(DisplayName="Speed Limit Zone end", Tooltip="End of zone with speed limit. StVO 274.2 Use TrafficSignValue::value and TrafficSignValue::value_unit to set the limit. Begin: TYPE_SPEED_LIMIT_ZONE_BEGIN"),
	TYPE_MINIMUM_SPEED_BEGIN = 55							UMETA(DisplayName="Minimum Speed begin", Tooltip="Start of mandatory minimum speed. StVO 275 Use TrafficSignValue::value and TrafficSignValue::value_unit to set the speed. End: TYPE_MINIMUM_SPEED_END"),
	TYPE_OVERTAKING_BAN_BEGIN = 56							UMETA(DisplayName="Overtaking Ban begin", Tooltip="Start of overtaking ban. StVO 276 End: TYPE_OVERTAKING_BAN_END"),
	TYPE_OVERTAKING_BAN_FOR_TRUCKS_BEGIN = 57				UMETA(DisplayName="Overtaking Ban for Trucks begin", Tooltip="Start of overtaking ban for trucks. StVO 277 End: TYPE_OVERTAKING_BAN_FOR_TRUCKS_END"),
	TYPE_SPEED_LIMIT_END = 58								UMETA(DisplayName="Speed Limit end", Tooltip="End of speed limit. StVO 278 Use TrafficSignValue::value and TrafficSignValue::value_unit to refer to the limit. Begin: TYPE_SPEED_LIMIT_BEGIN"),
	TYPE_MINIMUM_SPEED_END = 59								UMETA(DisplayName="Minimum Speed end", Tooltip="End of mandatory minimum speed. StVO 279 Use TrafficSignValue::value and TrafficSignValue::value_unit to refer to the limit. Begin: TYPE_MINIMUM_SPEED_BEGIN"),
	TYPE_OVERTAKING_BAN_END = 60							UMETA(DisplayName="Overtaking Ban end", Tooltip="End of overtaking ban. StVO 280 Begin: TYPE_OVERTAKING_BAN_BEGIN"),
	TYPE_OVERTAKING_BAN_FOR_TRUCKS_END = 61					UMETA(DisplayName="Overtaking Ban for Trucks end", Tooltip="End of overtaking ban for trucks. StVO 281 Begin: TYPE_OVERTAKING_BAN_FOR_TRUCKS_BEGIN"),
	TYPE_ALL_RESTRICTIONS_END = 62							UMETA(DisplayName="All Restrictions end", Tooltip="End of all speed and overtaking restrictions. StVO 282"),
	TYPE_NO_STOPPING = 63									UMETA(DisplayName="No Stopping", Tooltip="No stopping sign. StVO 283 Set Classification::direction_scope to DIRECTION_SCOPE_NO_DIRECTION StVO 283-10 StVO 283-11 Set Classification::direction_scope to DIRECTION_SCOPE_LEFT StVO 283-20 StVO 283-21 Set Classification::direction_scope to DIRECTION_SCOPE_RIGHT StVO 283-30 StVO 283-31 Set Classification::direction_scope to DIRECTION_SCOPE_LEFT_RIGHT"),
	TYPE_NO_PARKING = 64									UMETA(DisplayName="No Parking", Tooltip="No parking sign. StVO 286 Set Classification::direction_scope to DIRECTION_SCOPE_NO_DIRECTION StVO 286-10 StVO 286-11 Set Classification::direction_scope to DIRECTION_SCOPE_LEFT StVO 286-20 StVO 286-21 Set Classification::direction_scope to DIRECTION_SCOPE_RIGHT StVO 286-30 StVO 286-31 Set Classification::direction_scope to DIRECTION_SCOPE_LEFT_RIGHT As symbolic road marking RoadMarking::Classification::TYPE_SYMBOLIC_TRAFFIC_SIGN. StVO 299"),
	TYPE_NO_PARKING_ZONE_BEGIN = 65							UMETA(DisplayName="No Parking Zone begin", Tooltip="Begin of no parking zone. StVO 290.1 End: TYPE_NO_PARKING_ZONE_END"),
	TYPE_NO_PARKING_ZONE_END = 66							UMETA(DisplayName="No Parking Zone end", Tooltip="End of no parking zone. StVO 290.2 Begin: TYPE_NO_PARKING_ZONE_BEGIN"),
	TYPE_RIGHT_OF_WAY_NEXT_INTERSECTION = 67				UMETA(DisplayName="Right of Way at Next Intersection", Tooltip="Right of way at the next intersection. StVO 301"),
	TYPE_RIGHT_OF_WAY_BEGIN = 68							UMETA(DisplayName="Right of Way begin", Tooltip="Begin of priority road with right of way. StVO 306 End: TYPE_RIGHT_OF_WAY_END"),
	TYPE_RIGHT_OF_WAY_END = 69								UMETA(DisplayName="Right of Way end", Tooltip="End of priority road with right of way. StVO 307 Begin: TYPE_RIGHT_OF_WAY_BEGIN"),
	TYPE_PRIORITY_OVER_OPPOSITE_DIRECTION = 70				UMETA(DisplayName="Priority over Opposite Direction", Tooltip="Traffic has priority over vehicles from the opposite direction. StVO 308 See also: TYPE_PRIORITY_TO_OPPOSITE_DIRECTION"),
	TYPE_PRIORITY_OVER_OPPOSITE_DIRECTION_UPSIDE_DOWN = 71	UMETA(DisplayName="Priority over Opposite Direction upside down", Tooltip="Traffic has priority over vehicles from the opposite direction. StVO 308, upside down See also: TYPE_PRIORITY_OVER_OPPOSITE_DIRECTION"),
	TYPE_TOWN_BEGIN = 72									UMETA(DisplayName="Town begin", Tooltip="Town entrance. StVO 310 Use TrafficSignValue::text to denote the town's name and district, e.g. \"Wilster, Kreis Steinburg\". End: TYPE_TOWN_END"),
	TYPE_TOWN_END = 73										UMETA(DisplayName="Town end", Tooltip="Town exit. StVO 311 Use TrafficSignValue::text to denote the town's name and district, e.g. \"Wilster\". Begin: TYPE_TOWN_BEGIN "),
	TYPE_CAR_PARKING = 74									UMETA(DisplayName="Car Parking", Tooltip="Parking space. StVO 314 Set Classification::direction_scope to DIRECTION_SCOPE_NO_DIRECTION. StVO 314-50 Parking house Set Classification::direction_scope to DIRECTION_SCOPE_NO_DIRECTION. StVO 316 Park and ride Set Classification::direction_scope to DIRECTION_SCOPE_NO_DIRECTION. Set TrafficSignValue::text to \"P+R\". Park and move Set Classification::direction_scope to DIRECTION_SCOPE_NO_DIRECTION. Set TrafficSignValue::text to \"P+M\". StVO 317 Hiker\'s parking Set Classification::direction_scope to DIRECTION_SCOPE_NO_DIRECTION. StVO 318 Parking with parking disk 	Set Classification::direction_scope to DIRECTION_SCOPE_NO_DIRECTION. StVO 314-10 Set Classification::direction_scope to DIRECTION_SCOPE_LEFT. StVO 314-20 Set Classification::direction_scope to DIRECTION_SCOPE_RIGHT. StVO 314-30 Set Classification::direction_scope to DIRECTION_SCOPE_LEFT_RIGHT."),
	TYPE_CAR_PARKING_ZONE_BEGIN = 75						UMETA(DisplayName="Car Parking Zone begin", Tooltip="Begin of parking zone. StVO 314.1 End: TYPE_CAR_PARKING_ZONE_END"),
	TYPE_CAR_PARKING_ZONE_END = 76							UMETA(DisplayName="Car Parking Zone end", Tooltip="End of parking zone. StVO 314.2 Begin: TYPE_CAR_PARKING_ZONE_BEGIN"),
	TYPE_SIDEWALK_HALF_PARKING_LEFT = 172					UMETA(DisplayName="Sidewalk Half Parking left", Tooltip="Parking on sidewalks half in the direction of travel left. StVO 315-50 Right: TYPE_SIDEWALK_HALF_PARKING_RIGHT"),
	TYPE_SIDEWALK_HALF_PARKING_RIGHT = 173					UMETA(DisplayName="Sidewalk Half Parking right", Tooltip="Parking on sidewalks half in the direction of travel right. StVO 315-55 Left: TYPE_SIDEWALK_HALF_PARKING_LEFT"),
	TYPE_SIDEWALK_PARKING_LEFT = 174						UMETA(DisplayName="Sidewalk Parking left", Tooltip="Parking on sidewalks completely in the direction of travel left. StVO 315-60 Right: TYPE_SIDEWALK_PARKING_RIGHT"),
	TYPE_SIDEWALK_PARKING_RIGHT = 175						UMETA(DisplayName="Sidewalk Parking right", Tooltip="Parking on sidewalks completely in direction of travel right. StVO 315-65 Left: TYPE_SIDEWALK_PARKING_LEFT"),
	TYPE_SIDEWALK_PERPENDICULAR_HALF_PARKING_LEFT = 176		UMETA(DisplayName="Sidewalk Perpendicular Half Parking left", Tooltip="Parking on sidewalks half, perpendicular, in the direction of travel left. StVO 315-70 Right: TYPE_SIDEWALK_PERPENDICULAR_HALF_PARKING_RIGHT"),
	TYPE_SIDEWALK_PERPENDICULAR_HALF_PARKING_RIGHT = 177	UMETA(DisplayName="Sidewalk Perpendicular Half Parking right", Tooltip="Parking on sidewalks half, perpendicular, in the direction of travel right. StVO 315-75 Left: TYPE_SIDEWALK_PERPENDICULAR_HALF_PARKING_LEFT"),
	TYPE_SIDEWALK_PERPENDICULAR_PARKING_LEFT = 178			UMETA(DisplayName="Sidewalk Perpendicular Parking left", Tooltip="Parking on sidewalks, perpendicular, in the direction of travel left. StVO 315-80 Right: TYPE_SIDEWALK_PERPENDICULAR_PARKING_RIGHT"),
	TYPE_SIDEWALK_PERPENDICULAR_PARKING_RIGHT = 179			UMETA(DisplayName="Sidewalk Perpendicular Parking right", Tooltip="Parking on sidewalks, perpendicular, in the direction of travel right. StVO 315-85 Left: TYPE_SIDEWALK_PERPENDICULAR_PARKING_LEFT"),
	TYPE_LIVING_STREET_BEGIN = 77							UMETA(DisplayName="Living Street begin", Tooltip="Start of area with calmed / reduced traffic / home zone. StVO 325.1 End: TYPE_LIVING_STREET_END"),
	TYPE_LIVING_STREET_END = 78								UMETA(DisplayName="Living Street end", Tooltip="End of area with calmed / reduced traffic / home zone. StVO 325.2 Begin: TYPE_LIVING_STREET_BEGIN"),
	TYPE_TUNNEL = 79										UMETA(DisplayName="Tunnel", Tooltip="Tunnel ahead. StVO 327"),
	TYPE_EMERGENCY_STOPPING_LEFT = 80						UMETA(DisplayName="Emergency Stopping left", Tooltip="Emergency stopping place left. Note This type is to be applied in left-driving countries. Right: TYPE_EMERGENCY_STOPPING_RIGHT"),
	TYPE_EMERGENCY_STOPPING_RIGHT = 81						UMETA(DisplayName="Emergency Stopping right", Tooltip="Emergency stopping place right. StVO 328 Left: TYPE_EMERGENCY_STOPPING_LEFT"),
	TYPE_HIGHWAY_BEGIN = 82									UMETA(DisplayName="Highway begin", Tooltip="Begin of highway. StVO 330.1 End: TYPE_HIGHWAY_END"),
	TYPE_HIGHWAY_END = 83									UMETA(DisplayName="Highway end", Tooltip="End of highway. StVO 330.2 Begin: TYPE_HIGHWAY_BEGIN"),
	TYPE_EXPRESSWAY_BEGIN = 84								UMETA(DisplayName="Expressway begin", Tooltip="Begin of expressway for motor vehicles. StVO 331.1 End: TYPE_EXPRESSWAY_END"),
	TYPE_EXPRESSWAY_END = 85								UMETA(DisplayName="Expressway end", Tooltip="End of expressways for motor vehicles. StVO 331.2 Begin: TYPE_EXPRESSWAY_BEGIN"),
	TYPE_NAMED_HIGHWAY_EXIT = 183							UMETA(DisplayName="Named Highway exit", Tooltip="Highway exit. StVO 332 Use TrafficSignValue::text to denote the destination indicated in the sign, e.g. \"Mainz Wiesbaden\"."),
	TYPE_NAMED_EXPRESSWAY_EXIT = 184						UMETA(DisplayName="Named Expressway exit", Tooltip="Expressway exit. StVO 332.1 Use TrafficSignValue::text to denote the destination indicated in the sign, e.g. \"Mainz Wiesbaden\"."),
	TYPE_NAMED_ROAD_EXIT = 185								UMETA(DisplayName="Named Roat exit", Tooltip="Exit sign on other roads. StVO 332.1-20 Use TrafficSignValue::text to denote the destination indicated in the sign, e.g. \"Duisburg Endeninch\"."),
	TYPE_HIGHWAY_EXIT = 86									UMETA(DisplayName="Highway exit", Tooltip="Highway exit sign. StVO 333"),
	TYPE_EXPRESSWAY_EXIT = 186								UMETA(DisplayName="Expressway exit", Tooltip="Exit from expressway (arrow sign). StVO 333.1"),
	TYPE_ONEWAY_STREET = 187								UMETA(DisplayName="One way Street", Tooltip="One-way street. StVO 353 - Valid only until october 2022."),
	TYPE_CROSSING_GUARDS = 189								UMETA(DisplayName="Crossing Guards", Tooltip="Crossing guards. StVO 356"),
	TYPE_DEADEND = 190										UMETA(DisplayName="Dead End", Tooltip="Dead-end street. StVO 357"),
	TYPE_DEADEND_EXCLUDING_DESIGNATED_ACTORS = 191			UMETA(DisplayName="Dead End excluding Designated Actors", Tooltip="Dead-end street excluding ... StVO 357-50 excluding pedestrians and bicycles. StVO 357-51 excluding pedestrians. StVO 357-52 excluding bicycles."),
	TYPE_FIRST_AID_STATION = 194							UMETA(DisplayName="First Aid Station", Tooltip="First aid station. StVO 358"),
	TYPE_POLICE_STATION = 195								UMETA(DisplayName="Police Station", Tooltip="Police station. StVO 363"),
	TYPE_TELEPHONE = 196									UMETA(DisplayName="Telephone", Tooltip="Telephone service. StVO 365-50 Telephone service StVO 365-51 Emergency telephone service Use TrafficSignValue::text for \"SOS\"."),
	TYPE_FILLING_STATION = 198								UMETA(DisplayName="Filling Station", Tooltip="Filling station. StVO 365-52 Filling station.  StVO 365-53 LPG filling station. Use TrafficSignValue::text for \"LPG\". StVO 365-54 CNG filling station. Use TrafficSignValue::text for \"CNG\". StVO 365-65 Charging station for electric vehicles. Use TrafficSignValue::text for \"E\". StVO 365-66 H2 filling station. Use TrafficSignValue::text for \"H2\"."),
	TYPE_HOTEL = 201										UMETA(DisplayName="Hotel", Tooltip="Highway hotel. StVO 365-55"),
	TYPE_INN = 202											UMETA(DisplayName="Inn", Tooltip="Highway inn. StVO 365-56"),
	TYPE_KIOSK = 203										UMETA(DisplayName="Kiosk", Tooltip="Highway kiosk. StVO 365-57"),
	TYPE_TOILET = 204										UMETA(DisplayName="Toilet", Tooltip="Toilets. StVO 365-58"),
	TYPE_CHAPEL = 205										UMETA(DisplayName="Chapel", Tooltip="Highway chapel. StVO 365-59"),
	TYPE_TOURIST_INFO = 206									UMETA(DisplayName="Tourist Info", Tooltip="Tourist information. StVO 365-61"),
	TYPE_REPAIR_SERVICE = 207								UMETA(DisplayName="Repair Service", Tooltip="Roadside assistance. StVO 365-62"),
	TYPE_PEDESTRIAN_UNDERPASS = 208							UMETA(DisplayName="Pedestrian Underpass", Tooltip="Underpass for pedestrians. StVO 365-63"),
	TYPE_PEDESTRIAN_BRIDGE = 209							UMETA(DisplayName="Pedestrian Bridge", Tooltip="Pedestrian bridge. StVO 365-64"),
	TYPE_CAMPER_PLACE = 213									UMETA(DisplayName="Camper Place", Tooltip="Camper place. StVO 365-67 Camper and caravan place StVO 365-68"),
	TYPE_ADVISORY_SPEED_LIMIT_BEGIN = 214					UMETA(DisplayName="Advisory Speed Limit begin", Tooltip="Advisory speed limit beginning. StVO 380 - Valid only until october 2022. TrafficSignValue::value and TrafficSignValue::value_unit."),
	TYPE_ADVISORY_SPEED_LIMIT_END = 215						UMETA(DisplayName="Advisory Speed Limit end", Tooltip="Advisory speed limit end. StVO 381 - Valid only until october 2022 TrafficSignValue::value and TrafficSignValue::value_unit."),
	TYPE_PLACE_NAME = 216									UMETA(DisplayName="Place Name", Tooltip="Road passes through the town but not its city center. StVO 385 Use TrafficSignValue::text to denote the town indicated in the sign."),
	TYPE_TOURIST_ATTRACTION = 217							UMETA(DisplayName="Tourist Attraction", Tooltip="Tourist attraction. StVO 386.1 Use TrafficSignValue::text to denote the attraction indicated in the sign."),
	TYPE_TOURIST_ROUTE = 218								UMETA(DisplayName="Tourist Route", Tooltip="Tourist route. StVO 386.2 Use TrafficSignValue::text to denote the route indicated in the sign."),
	TYPE_TOURIST_AREA = 219									UMETA(DisplayName="Tourist Area", Tooltip="Geographical area containing several tourist attractions. StVO 386.3 Use TrafficSignValue::text to denote the area indicated in the sign."),
	TYPE_SHOULDER_NOT_PASSABLE_MOTOR_VEHICLES = 220			UMETA(DisplayName="Shoulder not Passable Motor Vehicles", Tooltip="Shoulder unsafe for multi-track motor vehicles. StVO 388 - Valid only until october 2022"),
	TYPE_SHOULDER_UNSAFE_TRUCKS_TRACTORS = 221				UMETA(DisplayName="Shoulder unsafe Trucks Tractors", Tooltip="Shoulder unsafe for vehicles with a permitted gross weight over 3.5 t and for tractors. StVO 389 - Valid only until october 2022"),
	TYPE_TOLL_BEGIN = 222									UMETA(DisplayName="Toll begin", Tooltip="Toll highway beginning. StVO 390"),
	TYPE_TOLL_END = 223										UMETA(DisplayName="Toll end", Tooltip="Toll highway end. StVO 390.2"),
	TYPE_TOLL_ROAD = 224									UMETA(DisplayName="Toll Road", Tooltip="Toll road. StVO 391"),
	TYPE_CUSTOMS = 225										UMETA(DisplayName="Customs", Tooltip="Customs post. StVO 392"),
	TYPE_INTERNATIONAL_BORDER_INFO = 226					UMETA(DisplayName="International Border Info", Tooltip="Information sign posted at international borders.StVO 393"),
	TYPE_STREETLIGHT_RED_BAND = 227							UMETA(DisplayName="Streetlight Red Band", Tooltip="Red band on lamp posts indicate that streetlight does not stay on all night. StVO 394 StVO 394-50"),
	TYPE_FEDERAL_HIGHWAY_ROUTE_NUMBER = 228					UMETA(DisplayName="Federal Highway Route Number", Tooltip="Federal Highway route number. StVO 401"),
	TYPE_HIGHWAY_ROUTE_NUMBER = 229							UMETA(DisplayName="Highway Route Number", Tooltip="Highway route number. StVO 405 Use TrafficSignValue::text to denote the route number indicated in the sign."),
	TYPE_HIGHWAY_INTERCHANGE_NUMBER = 230					UMETA(DisplayName="Highway Interchange Number", Tooltip="Highway interchange number (exits, three and four-way interchanges). StVO 406-50 StVO 406-51 Use TrafficSignValue::text to denote the route number indicated in the sign."),
	TYPE_EUROPEAN_ROUTE_NUMBER = 231						UMETA(DisplayName="European Route Number", Tooltip="European route number. StVO 410 Use TrafficSignValue::text to denote the route number indicated in the sign."),
	TYPE_FEDERAL_HIGHWAY_DIRECTION_LEFT = 232				UMETA(DisplayName="Federal Highway Direction left", Tooltip="Federal highway direction sign, left. StVO 415-10 Right: TYPE_FEDERAL_HIGHWAY_DIRECTION_RIGHT"),
	TYPE_FEDERAL_HIGHWAY_DIRECTION_RIGHT = 233				UMETA(DisplayName="Federal Highway Direction right", Tooltip="Federal highway direction sign, right. StVO 415-20 Left: TYPE_FEDERAL_HIGHWAY_DIRECTION_LEFT"),
	TYPE_PRIMARY_ROAD_DIRECTION_LEFT = 234					UMETA(DisplayName="Primary Road Direction left", Tooltip="Primary road direction sign, left. StVO 418-10 Right: TYPE_PRIMARY_ROAD_DIRECTION_RIGHT"),
	TYPE_PRIMARY_ROAD_DIRECTION_RIGHT = 235					UMETA(DisplayName="Primary Road Direction right", Tooltip="Primary road direction sign, right. StVO 418-20 Left: TYPE_PRIMARY_ROAD_DIRECTION_LEFT"),
	TYPE_SECONDARY_ROAD_DIRECTION_LEFT = 236				UMETA(DisplayName="Secondary Road Direction right", Tooltip="Secondary road direction sign, left. StVO 419-10 Use TrafficSignValue::text to denote the destination indicated in the sign. Right: TYPE_SECONDARY_ROAD_DIRECTION_RIGHT"),
	TYPE_SECONDARY_ROAD_DIRECTION_RIGHT = 237				UMETA(DisplayName="Secondary Road Direction left", Tooltip="Secondary road direction sign, right. StVO 419-20 Use TrafficSignValue::text to denote the destination indicated in the sign. Left: TYPE_SECONDARY_ROAD_DIRECTION_LEFT"),
	TYPE_DIRECTION_DESIGNATED_ACTORS_LEFT = 238				UMETA(DisplayName="Direction Designated Actors left", Tooltip="Advance direction sign for designated type of vehicle, left. StVO 421-10 StVO 421-11 StVO 421-12 Right: TYPE_DIRECTION_DESIGNATED_ACTORS_RIGHT"),
	TYPE_DIRECTION_DESIGNATED_ACTORS_RIGHT = 239			UMETA(DisplayName="Direction Designated Actors right", Tooltip="Advance direction sign for designated type of vehicle, right. StVO 421-20 StVO 421-21 StVO 421-22 Left: TYPE_DIRECTION_DESIGNATED_ACTORS_LEFT"),
	TYPE_ROUTING_DESIGNATED_ACTORS = 240					UMETA(DisplayName="Routing Designated Actors", Tooltip="Routing for designated type of vehicle, left. StVO 422-10 StVO 422-12 StVO 422-14 StVO 422-16 Routing for designated type of vehicle, align left. StVO 422-11 StVO 422-13 StVO 422-15 StVO 422-17 Direction preannouncement sign for designated type of vehicle, left. StVO 442-10 StVO 442-12 StVO 442-13 Routing or designated type of vehicle, right. StVO 422-20 StVO 422-22 StVO 422-24	StVO 422-26 Routing for designated type of vehicle, align right. StVO 422-21 StVO 422-23 StVO 422-25 StVO 422-27 Direction preannouncement sign for designated type of vehicle, right. StVO 442-20 StVO 442-22 StVO 442-23 Routing for designated type of vehicle, straight. StVO 422-30 StVO 422-32 StVO 422-34 StVO 422-36 Note OSI 4.0 will describe the actors and arrows similar to the supplementary signs approach."),
	TYPE_DIRECTION_TO_HIGHWAY_LEFT = 143					UMETA(DisplayName="Direction to Highway left", Tooltip="Direction to highway, left. StVO 430-10 Right: TYPE_DIRECTION_TO_HIGHWAY_RIGHT"),
	TYPE_DIRECTION_TO_HIGHWAY_RIGHT = 108					UMETA(DisplayName="Direction to Highway right", Tooltip="Direction to highway, right. StVO 430-20 Left: TYPE_DIRECTION_TO_HIGHWAY_LEFT"),
	TYPE_DIRECTION_TO_LOCAL_DESTINATION_LEFT = 127			UMETA(DisplayName="Direction to Local Destination left", Tooltip="Direction sign to important local destinations, left. StVO 432-10 Use TrafficSignValue::text to denote the destination indicated in the sign. Right: TYPE_DIRECTION_TO_LOCAL_DESTINATION_RIGHT"),
	TYPE_DIRECTION_TO_LOCAL_DESTINATION_RIGHT = 136			UMETA(DisplayName="Direction to Local Destination right", Tooltip="Direction sign to important local destinations, right. StVO 432-20 Use TrafficSignValue::text to denote the destination indicated in the sign. Left: TYPE_DIRECTION_TO_LOCAL_DESTINATION_LEFT"),
	TYPE_CONSOLIDATED_DIRECTIONS = 118						UMETA(DisplayName="Consolidated Directions", Tooltip="Consolidated direction sign. StVO 434-50 StVO 434-51 StVO 434-52 StVO 434-53"),
	TYPE_STREET_NAME = 119									UMETA(DisplayName="Street Name", Tooltip="Street name sign. StVO 437 Use TrafficSignValue::text to denote the street name."),
	TYPE_DIRECTION_PREANNOUNCEMENT = 120					UMETA(DisplayName="Direction Preannouncement", Tooltip="Direction preannouncement sign. StVO 438"),
	TYPE_DIRECTION_PREANNOUNCEMENT_LANE_CONFIG = 121		UMETA(DisplayName="Direction Preannouncement Lane Config", Tooltip="Direction preannouncement sign including lane configuration. StVO 439"),
	TYPE_DIRECTION_PREANNOUNCEMENT_HIGHWAY_ENTRIES = 122	UMETA(DisplayName="Direction Preannouncement Highway Entries", Tooltip="Direction preannouncement sign including highway entries. StVO 440"),
	TYPE_HIGHWAY_ANNOUNCEMENT = 123							UMETA(DisplayName="Highway Announcement", Tooltip="Highway announcement board. StVO 448 Use TrafficSignValue::value and TrafficSignValue::value_unit to set the distance. Use TrafficSignValue::text to denote the highway and the direction indicated in the sign, e.g. \"26 Duesseldorf - Benrath\"."),
	TYPE_OTHER_ROAD_ANNOUNCEMENT = 124						UMETA(DisplayName="Other Road Announcement", Tooltip="Announcement board on other roads outside of highways. StVO 448-50 Use TrafficSignValue::value and TrafficSignValue::value_unit to set the distance. Use TrafficSignValue::text to denote the destination indicated in the sign."),
	TYPE_HIGHWAY_ANNOUNCEMENT_TRUCK_STOP = 125				UMETA(DisplayName="Highway Announcement Truck Stop", Tooltip="Announcement highway truck stop. StVO 448.1"),
	TYPE_HIGHWAY_PREANNOUNCEMENT_DIRECTIONS = 126			UMETA(DisplayName="Highway Preannouncement Directions", Tooltip="Highway interchange advance directional sign. StVO 449"),
	TYPE_POLE_EXIT = 88										UMETA(DisplayName="Pole Exit", Tooltip="Pole indicating highways exit in ... m. StVO 450-50 StVO 450-51 StVO 450-52 StVO 450-53 StVO 450-54 StVO 450-55 Use TrafficSignValue::value and TrafficSignValue::value_unit to specify the distance in m or the displayed number of stripes (in that case, set TrafficSignValue::value_unit to TrafficSignValue::UNIT_NO_UNIT.)."),
	TYPE_HIGHWAY_DISTANCE_BOARD = 180						UMETA(DisplayName="Highway Distance Board", Tooltip="Highway distance board. StVO 453 StVO 453-50"),
	TYPE_DETOUR_LEFT = 181									UMETA(DisplayName="Detour Left", Tooltip="Detour sign, pointing left. StVO 454-10 Right: TYPE_DETOUR_RIGHT"),
	TYPE_DETOUR_RIGHT = 182									UMETA(DisplayName="Detour Right", Tooltip="Detour sign, pointing right. StVO 454-20 Left: TYPE_DETOUR_LEFT"),
	TYPE_NUMBERED_DETOUR = 131								UMETA(DisplayName="Numbered Detour", Tooltip="Numbered detour route. StVO 455.1 Use TrafficSignValue::text to denote the alternative routing name indicated in the sign. Note OSI 4.0 will describe the arrows similar to the supplementary signs approach."),
	TYPE_DETOUR_BEGIN = 132									UMETA(DisplayName="Detour begin", Tooltip="Announcement; begin of detour. StVO 457.1"),
	TYPE_DETOUR_END = 133									UMETA(DisplayName="Detour end", Tooltip="End of detour. StVO 457.2"),
	TYPE_DETOUR_ROUTING_BOARD = 134							UMETA(DisplayName="Detour Routing Board", Tooltip="Diversion routing board. StVO 458"),
	TYPE_OPTIONAL_DETOUR = 111								UMETA(DisplayName="Optional Detour", Tooltip="The sign indicates an alternative routing. StVO 460-50 	The sign indicates an alternative routing, announcement. StVO 460-10 	The sign indicates an alternative routing, preannouncement left. StVO 460-11 The sign indicates an alternative routing, left. StVO 460-12 The sign indicates an alternative routing, change lane left. StVO 460-20 The sign indicates an alternative routing, preannouncement right. StVO 460-21 The sign indicates an alternative routing, right. StVO 460-22 The sign indicates an alternative routing, lane change right. StVO 460-30 	The sign indicates an alternative routing, straight. Use TrafficSignValue::text to denote the alternative routing name indicated in the sign. Note OSI 4.0 will describe the arrows similar to the supplementary signs approach."),
	TYPE_OPTIONAL_DETOUR_ROUTING = 199						UMETA(DisplayName="Optional Detour Routing", Tooltip="Provisional diversion route schematic. StVO 466"),
	TYPE_ROUTE_RECOMMENDATION = 211							UMETA(DisplayName="Route Recommendation", Tooltip="Recommended alternate route. StVO 467.1-10 Set Classification::direction_scope as DIRECTION_SCOPE_LEFT. StVO 467.1-20 Set Classification::direction_scope as DIRECTION_SCOPE_RIGHT."),
	TYPE_ROUTE_RECOMMENDATION_END = 212						UMETA(DisplayName="Route Recommendation end", Tooltip="End of recommended alternate route. StVO 467.2"),
	TYPE_ANNOUNCE_LANE_TRANSITION_LEFT = 192				UMETA(DisplayName="Announce Lane Transition left", Tooltip="X lanes transition, left. StVO 501-10 One associated lane. StVO 501-11 Two associated lanes. StVO 501-12 Three associated lanes. (StVO 505-11) Two associated lanes with restriction. Restriction defined as additional main sign. (StVO 505-12) Three associated lanes with restriction. Restrictions defined as additional main sign(s). Right: TYPE_ANNOUNCE_LANE_TRANSITION_RIGHT"),
	TYPE_ANNOUNCE_LANE_TRANSITION_RIGHT = 193				UMETA(DisplayName="Announce Lane Transition right", Tooltip="X lanes transition, right. StVO 501-20 One associated lane. StVO 501-21 Two associated lanes. StVO 501-22 Three associated lanes. (StVO 505-21) Two associated lanes with restriction. Restriction defined as additional main sign. (StVO 505-22) Three associated lanes with restriction. Restrictions defined as additional main sign(s). Left: TYPE_ANNOUNCE_LANE_TRANSITION_LEFT"),
	TYPE_ANNOUNCE_RIGHT_LANE_END = 90						UMETA(DisplayName="Announce right Lane end", Tooltip="End of X right lanes. StVO 531-10 As symbolic road marking RoadMarking::Classification::TYPE_SYMBOLIC_TRAFFIC_SIGN. StVO 297.1-21"),
	TYPE_ANNOUNCE_LEFT_LANE_END = 89						UMETA(DisplayName="Announce left Lane end", Tooltip="End of X left lanes. StVO 531-20 As symbolic road marking RoadMarking::Classification::TYPE_SYMBOLIC_TRAFFIC_SIGN. StVO 297.1-21"),
	TYPE_ANNOUNCE_RIGHT_LANE_BEGIN = 115					UMETA(DisplayName="Announce right Lane begin", Tooltip="Begin of X right lanes.Left: TYPE_ANNOUNCE_LEFT_LANE_BEGIN"),
	TYPE_ANNOUNCE_LEFT_LANE_BEGIN = 116						UMETA(DisplayName="Announce left Lane begin", Tooltip="Begin of X left lanes. (StVO 545-11) Extension from two to three lanes with minimum speed by lane. 	Restrictions defined as additional main signs. Right: TYPE_ANNOUNCE_RIGHT_LANE_BEGIN"),
	TYPE_ANNOUNCE_LANE_CONSOLIDATION = 117					UMETA(DisplayName="Announce Lane Consolidation", Tooltip="Announce lane consolidation. StVO 551-20 Consolidation of lanes from multiple roads, one continuing, one opening. StVO 551-21 Consolidation of lanes from multiple roads, two continuing, one opening. StVO 551-22 Consolidation of lanes from multiple roads, two continuing, two opening. StVO 551-23 Consolidation of lanes from multiple roads, three continuing, two opening. StVO 551-24 Consolidation of lanes from multiple roads, three continuing, one opening."),
	TYPE_DETOUR_CITY_BLOCK = 142							UMETA(DisplayName="Detour City Block", Tooltip="Announce lane consolidation. StVO 551-20 Consolidation of lanes from multiple roads, one continuing, one opening. StVO 551-21 Consolidation of lanes from multiple roads, two continuing, one opening. StVO 551-22 Consolidation of lanes from multiple roads, two continuing, two opening. StVO 551-23 Consolidation of lanes from multiple roads, three continuing, two opening. StVO 551-24 Consolidation of lanes from multiple roads, three continuing, one opening."),
	TYPE_GATE = 141											UMETA(DisplayName="Gate", Tooltip="Boom gate. StVO 600"),
	TYPE_POLE_WARNING = 91									UMETA(DisplayName="Pole Warning", Tooltip="Pole for warning and guiding purposes (red/white stripes - StVO 605, also StVO 628 and StVO 629). StVO 605 StVO 628 StVO 629 Variants (here X can be any of 605, 628 or 629): StVO X-10, -12, -13 and -14 Set vertically_mirrored to false. StVO X-11 Set Classification::direction_scope as DIRECTION_SCOPE_RIGHT. StVO X-20, -22, -23 and -24 Set vertically_mirrored to true. StVO X-21 Set Classification::direction_scope as DIRECTION_SCOPE_LEFT."),
	TYPE_TRAFFIC_CONE = 140									UMETA(DisplayName="Traffic Cone", Tooltip="Traffic cone. StVO 610"),
	TYPE_MOBILE_LANE_CLOSURE = 139							UMETA(DisplayName="Mobile Lane Closure", Tooltip="Mobile lane closure board. StVO 615 no arrow StVO 616-30 with lighted arrow, large StVO 616-31 with lighted arrow, small Note Additional traffic signs are modelled as separate main signs."),
	TYPE_REFLECTOR_POST = 114								UMETA(DisplayName="Reflector Post", Tooltip="Reflector guide posts. StVO 620-40 Reflector guide posts, rectangular reflecting. StVO 621-40 Reflector guide posts, two dots reflecting. Note No reflecting color is specified."),
	TYPE_DIRECTIONAL_BOARD_WARNING = 113					UMETA(DisplayName="Directional Board Warning", Tooltip="Directional board used for warning and guiding purposes (red/white stripes - StVO 625). Use the optional attribute Classification::direction_scope to specify the direction the wedge symbols are pointing at. Variants (here X is any of 0, 1, 2, 3): StVO 625-1X Set Classification::direction_scope as DIRECTION_SCOPE_LEFT. Optionally, use TrafficSignValue::value to specify the number of wedges on the board. If you do so, set TrafficSignValue::value_unit to TrafficSignValue::UNIT_NO_UNIT. StVO 625-2X Set Classification::direction_scope as DIRECTION_SCOPE_RIGHT. Optionally, use TrafficSignValue::value to specify the number of wedges on the board. If you do so, set TrafficSignValue::value_unit to TrafficSignValue::UNIT_NO_UNIT."),
	TYPE_GUIDING_PLATE = 104								UMETA(DisplayName="Guinding Plate", Tooltip="Guiding plate. StVO 626-10 Set vertically_mirrored to false. StVO 626-20 Set vertically_mirrored to true."),
	TYPE_GUIDING_PLATE_WEDGES = 105							UMETA(DisplayName="Guiding Plate Wedges", Tooltip="Guiding plate, wedges. StVO 626-30, 626-31"),
	TYPE_PARKING_HAZARD = 99								UMETA(DisplayName="Parking Hazard", Tooltip="Parking hazard. StVO 630-10 Set vertically_mirrored to false. StVO 630-20 Set vertically_mirrored to true."),
	TYPE_TRAFFIC_LIGHT_GREEN_ARROW = 92						UMETA(DisplayName="Traffic Light Green Arrow", Tooltip="Green arrow sign at a traffic light. StVO 720")
};

UENUM(BlueprintType)
enum class ESupplementarySignType : uint8
{
	TYPE_UNKNOWN = 0											UMETA(Hidden, DisplayName="Unknown", Tooltip="Type of supplementary sign is unknown (must not be used in ground truth)."),
  	TYPE_OTHER = 1												UMETA(DisplayName="Other", Tooltip="Other (unspecified but known) type of supplementary sign."),
  	TYPE_NO_SIGN = 2											UMETA(DisplayName="No Sign", Tooltip="There is no supplementary sign (must not be used in ground truth)."),
  	TYPE_TEXT = 41												UMETA(DisplayName="Text", Tooltip="Text sign. Use it as a canvas for text-only signs: Use TrafficSignValue::value to indicate a numerical value indicated on the sign. Accompany this value with an indication of its unit of measure given by TrafficSignValue::value_unit. Use TrafficSignValue::text to indicate a string of text indicated on the sign. See https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1TrafficSign_1_1SupplementarySign_1_1Classification.html for more information"),
	TYPE_SPACE = 39												UMETA(DisplayName="Space", Tooltip="Text sign with distance indication. Use it as a canvas for text signs that make reference to a point or area in space: Use TrafficSignValue::value to include the distance indicated in the sign. Accompany this value with an indication of its unit of measure given by TrafficSignValue::value_unit (e.g. m), Use TrafficSignValue::text to indicate the sign's specific text"),
	TYPE_TIME = 26												UMETA(DisplayName="Time", Tooltip="Text sign with time indication. Use it as a canvas for text signs that make: reference to a point in time or a time range. Use one or more TrafficSignValue messages to include the times indicated in the sign. Accompany each value with an indication of its unit of measure given by TrafficSignValue::value_unit, e.g. h. For each TrafficSignValue, TrafficSignValue::value indicates the time elapsed since midnight every day.Use the TrafficSignValue::text member of the first TrafficSignValue message to indicate the sign's specific text. Note Time interval need two TrafficSignValue messages, one to indicate their start and one to indicate their end. In case more than one time range is required, the TrafficSignValue::value member of the first TrafficSignValue message is interpreted as the beginning of the first interval, the TrafficSignValue::value member of the second TrafficSignValue message is interpreted as the end of the first interval, and so on."),
	TYPE_ARROW = 30												UMETA(DisplayName="Arrow", Tooltip="A supplementary sign showing a direction alone. Use together with the message Classification::arrow."),
	TYPE_CONSTRAINED_TO = 46									UMETA(DisplayName="Constrained To", Tooltip="The list of traffic actors to which the main sign's regulation is constrained to. Use as many members of the Actor enumerator as needed to denote the related traffic actors."),
	TYPE_EXCEPT = 45											UMETA(DisplayName="Except", Tooltip="The list of traffic actors for which the main sign's regulation does not apply or have a special driving allowance. Use as many members of the Actor enumerator as needed to denote the excepted traffic actors: Note In the German StVO, these signs include the word \"frei\"."),
  	TYPE_VALID_FOR_DISTANCE = 3									UMETA(DisplayName="Valid For Distance", Tooltip="Traffic sign is valid for a certain distance. Use TrafficSignValue::value and TrafficSignValue::value_unit (e.g. m) to indicate the distance."),
	TYPE_PRIORITY_ROAD_BOTTOM_LEFT_FOUR_WAY = 27				UMETA(DisplayName="Priority Road Bottom Left Four Way", Tooltip="Priority road from bottom to left in the intersection. StVO 1002-10"),
	TYPE_PRIORITY_ROAD_TOP_LEFT_FOUR_WAY = 28					UMETA(DisplayName="Priority Road Top Left Four Way", Tooltip="Priority road from top to left in the intersection. StVO 1002-11"),
	TYPE_PRIORITY_ROAD_BOTTOM_LEFT_THREE_WAY_STRAIGHT = 32		UMETA(DisplayName="Priority Road Bottom Left Three Way Straight", Tooltip="Priority road from bottom to left, junction from above. StVO 1002-12"),
	TYPE_PRIORITY_ROAD_BOTTOM_LEFT_THREE_WAY_SIDEWAYS = 33		UMETA(DisplayName="Priority Road Bottom Left Three Way Sideways", Tooltip="Priority road from bottom to left, junction from the right. StVO 1002-13"),
	TYPE_PRIORITY_ROAD_TOP_LEFT_THREE_WAY_STRAIGHT = 34			UMETA(DisplayName="Priority Road Top Left Three Way Straight", Tooltip="Priority road from top to left, junction from below. StVO 1002-14"),
	TYPE_PRIORITY_ROAD_BOTTOM_RIGHT_FOUR_WAY = 29				UMETA(DisplayName="Priority Road Bottom Right Four Way", Tooltip="Priority road from bottom to right in the intersection. StVO 1002-20"),
	TYPE_PRIORITY_ROAD_TOP_RIGHT_FOUR_WAY = 31					UMETA(DisplayName="Priority Road Top Right Four Way", Tooltip="Priority road from top to right in the intersection. StVO 1002-21"),
	TYPE_PRIORITY_ROAD_BOTTOM_RIGHT_THREE_WAY_STRAIGHT = 35		UMETA(DisplayName="Priority Road Bottom Right Three Way Straight", Tooltip="Priority road from bottom to right, junction from above. StVO 1002-22"),
	TYPE_PRIORITY_ROAD_BOTTOM_RIGHT_THREE_WAY_SIDEWAY = 36		UMETA(DisplayName="Priority Road Bottom Right Three Way Sideway", Tooltip="Priority road from bottom to right, junction from the left. StVO 1002-23"),
	TYPE_PRIORITY_ROAD_TOP_RIGHT_THREE_WAY_STRAIGHT = 37		UMETA(DisplayName="Priority Road Top Right Three Way Straight", Tooltip="Priority road from top to right, junction from below. StVO 1002-24"),
	TYPE_VALID_IN_DISTANCE = 4									UMETA(DisplayName="Valid In Distance", Tooltip="Distance to the start of validity of the traffic sign. StVO 1004-30 StVO 1004-31 Use TrafficSignValue::value and TrafficSignValue::value_unit (e.g. m) to indicate the distance. Note For OSI 4.0 compatibility use TYPE_SPACE instead."),
	TYPE_STOP_IN = 25											UMETA(DisplayName="Stop In", Tooltip="Stop in e.g... m. StVO 1004-32 Use TrafficSignValue::value and TrafficSignValue::value_unit (e.g. m) to indicate the distance. Note For OSI 4.0 compatibility use TYPE_SPACE instead."),
	TYPE_LEFT_ARROW = 11										UMETA(DisplayName="Left Arrow", Tooltip="Direction, left-pointing. StVO 1000-10 Note For OSI 4.0 compatibility use TYPE_ARROW instead."),
	TYPE_LEFT_BEND_ARROW = 13									UMETA(DisplayName="Left Bend Arrow", Tooltip="Direction of potential danger, left-pointing. StVO 1000-11 Note For OSI 4.0 compatibility use TYPE_ARROW instead."),
	TYPE_RIGHT_ARROW = 12										UMETA(DisplayName="Right Arrow", Tooltip="Direction, right-pointing. StVO 1000-20 Note For OSI 4.0 compatibility use TYPE_ARROW instead."),
	TYPE_RIGHT_BEND_ARROW = 14									UMETA(DisplayName="Right Bend Arrow", Tooltip="Direction of potential danger, right-pointing. StVO 1000-21 Note For OSI 4.0 compatibility use TYPE_ARROW instead."),
	TYPE_ACCIDENT = 40											UMETA(DisplayName="Accident", Tooltip="Accident hazard. StVO 1006-31 See also: TYPE_TEXT."),
	TYPE_SNOW = 9												UMETA(DisplayName="Snow", Tooltip="Restriction of the validity of the traffic sign to snowy / icy conditions. StVO 1007-30 Note The identifier \"StVO 1007-30\" was used to denote a restriction of the validity of the traffic sign to snowy / icy conditions until the edition of 2013 of the official Catalog of Street Signs of the Federal Road Research Institute of Germany - BASt. Since the edition corresponding to 2017, \"StVO 1007-30\" is used to denote the hazard of oil trails. See TYPE_OIL."),
	TYPE_FOG = 8												UMETA(DisplayName="Fog", Tooltip="Restriction of the validity of the traffic sign to foggy conditions. StVO 1007-61 Note For OSI 4.0 compatibility use TYPE_TEXT instead."),
	TYPE_ROLLING_HIGHWAY_INFORMATION = 48						UMETA(DisplayName="Rolling Highway Information", Tooltip="Information on rolling highway.StVO 1010-14"),
	TYPE_SERVICES = 47											UMETA(DisplayName="Services", Tooltip="Information about services. StVO 1010-15"),
	TYPE_TIME_RANGE = 5											UMETA(DisplayName="Time Range", Tooltip="Time range for validity of traffic sign. StVO 1040-30 StVO 1042-33 Use one TrafficSignValue message to indicate the start of the time range and one TrafficSignValue message to indicate the end of the time range. For each TrafficSignValue, TrafficSignValue::value indicates the time elapsed since midnight each day, and TrafficSignValue::value_unit indicates the unit this time is expressed in, e.g. in min. If including start and end days of the week, include two additional TrafficSignValue messages. For these messages, use TrafficSignValue::value_unit as TrafficSignValue::UNIT_NO_UNIT and TrafficSignValue::value as an integer from 1 to 7, where 1 denotes Monday and 7 denotes Sunday. Note For OSI 4.0 compatibility use TYPE_TIME instead."),
	TYPE_PARKING_DISC_TIME_RESTRICTION = 43						UMETA(DisplayName="Parking Disc Restriction", Tooltip="Parking disc restrictions. StVO 1040-32 	Parking disc restriction 	Use TrafficSignValue::value and TrafficSignValue::value_unit (e.g. min) to indicate the allowed duration of parking. StVO 1040-33 	Parking disc restriction for marked parking areas 	Use TrafficSignValue::value and TrafficSignValue::value_unit (e.g. min) to indicate the allowed duration of parking. Set TrafficSignValue::text to \”in gekennzeichneten Flächen\”."),
	TYPE_WEIGHT = 6												UMETA(DisplayName="Weight", Tooltip="Restriction of the validity of the traffic sign depending on the vehicle's weight. StVO 1053-33 StVO 1053-37 StVO 1060-33 Use TrafficSignValue::value and TrafficSignValue::value_unit (e.g. in t) to indicate the weight."),
	TYPE_WET = 44												UMETA(DisplayName="Wet", Tooltip="	If \"wet surface\". StVO 1053-35"),
	TYPE_PARKING_CONSTRAINT = 42								UMETA(DisplayName="Parking Constraint", Tooltip="Parking constraints. StVO 1053-38 pull in crosswise StVO 1053-39 pull in diagonally"),
	TYPE_NO_WAITING_SIDE_STRIPES = 38							UMETA(DisplayName="No Waiting Side Stripes", Tooltip="No parking, also on verges/shoulder. StVO 1060-31"),
	TYPE_RAIN = 7												UMETA(DisplayName="Rain", Tooltip="Restriction of the validity of the traffic sign to wet / rainy conditions. (No German StVO-Nr., Austrian StVO 1960 supplementary sign g)."),
	TYPE_SNOW_RAIN = 10											UMETA(DisplayName="Snow Rain", Tooltip="Combined restriction of the validity of the traffic sign to rainy or snowy conditions denoted by a single supplementary sign (instead of two signs of TYPE_RAIN and TYPE_SNOW respectively). (StVO -, Austria)"),
  	TYPE_NIGHT = 19												UMETA(DisplayName="Night", Tooltip="Valid at night."),
  	TYPE_STOP_4_WAY = 21										UMETA(DisplayName="Stop 4 Way", Tooltip="Stop 4 way."),
	TYPE_TRUCK = 15												UMETA(DisplayName="Truck", Tooltip="Trucks. Note For OSI 4.0 compatibility use the message Actor instead."),
	TYPE_TRACTORS_MAY_BE_PASSED = 16							UMETA(DisplayName="Tractors May Be Passed", Tooltip="Tractors may be passed. Note For OSI 4.0 compatibility use the message Actor instead."),
	TYPE_HAZARDOUS = 17											UMETA(DisplayName="Hazardous", Tooltip="Vehicles transporting hazardous goods. Note For OSI 4.0 compatibility use the message Actor instead."),
	TYPE_TRAILER = 18											UMETA(DisplayName="Trailer", Tooltip="Trailers. Note For OSI 4.0 compatibility use the message Actor instead."),
	TYPE_ZONE = 20												UMETA(DisplayName="Zone", Tooltip="Zone. Note For OSI 4.0 compatibility use the message Actor instead."),
	TYPE_MOTORCYCLE = 22										UMETA(DisplayName="Motorcycle", Tooltip="Motorcycles. Note For OSI 4.0 compatibility use the message Actor instead."),
	TYPE_MOTORCYCLE_ALLOWED = 23								UMETA(DisplayName="Motorcycle Allowed", Tooltip="Motorcycles allowed. Note For OSI 4.0 compatibility use the message Actor instead."),
	TYPE_CAR = 24												UMETA(DisplayName="Car", Tooltip="Cars. Note For OSI 4.0 compatibility use the message Actor instead.")
};

UENUM(BlueprintType)
enum class ESignActor : uint8
{
	ACTOR_UNKNOWN = 0							UMETA(Hidden, DisplayName="Unknown", Tooltip="An unknown actor."),
	ACTOR_OTHER = 1								UMETA(DisplayName="Other", Tooltip="Other actor (specified but known)"),
	ACTOR_NO_ACTOR = 2							UMETA(DisplayName="No Actor", Tooltip="The actor is not specified."),
	ACTOR_AGRICULTURAL_VEHICLES = 3				UMETA(DisplayName="Agricultural Vehicles", Tooltip="Agricultural vehicles."),
	ACTOR_BICYCLES = 4							UMETA(DisplayName="Bicycles", Tooltip="Bicycles."),
	ACTOR_BUSES = 5								UMETA(DisplayName="Buses", Tooltip="Buses."),
	ACTOR_CAMPERS = 6							UMETA(DisplayName="Campers", Tooltip="Campers."),
	ACTOR_CARAVANS = 7							UMETA(DisplayName="Campers", Tooltip="Campers."),
	ACTOR_CARS = 8								UMETA(DisplayName="Cars", Tooltip="Cars."),
	ACTOR_CARS_WITH_CARAVANS = 9				UMETA(DisplayName="Cars with Caravans", Tooltip="Cars with caravans."),
	ACTOR_CARS_WITH_TRAILERS = 10				UMETA(DisplayName="Cars with Trailers", Tooltip="Cars with trailers."),
	ACTOR_CATTLE = 11							UMETA(DisplayName="Cattle", Tooltip="Cattles."),
	ACTOR_CHILDREN = 12							UMETA(DisplayName="Children", Tooltip="Children."),
	ACTOR_CONSTRUCTION_VEHICLES = 13			UMETA(DisplayName="Construction Vehicles", Tooltip="Construction vehicles."),
	ACTOR_DELIVERY_VEHICLES = 14				UMETA(DisplayName="Delivery Vehicles", Tooltip="Delivery vehicles."),
	ACTOR_DISABLED_PERSONS = 15					UMETA(DisplayName="Disabled Persons", Tooltip="Disabled persons."),
	ACTOR_EBIKES = 16							UMETA(DisplayName="E-Bikes", Tooltip="E-bikes."),
	ACTOR_ELECTRIC_VEHICLES = 17				UMETA(DisplayName="Electric Vehicles", Tooltip="Electric vehicles."),
	ACTOR_EMERGENCY_VEHICLES = 18				UMETA(DisplayName="Emergency Vehicles", Tooltip="Emergency vehicles."),
	ACTOR_FERRY_USERS = 19						UMETA(DisplayName="Ferry Users", Tooltip="Ferry users."),
	ACTOR_FORESTRY_VEHICLES = 20				UMETA(DisplayName="Forestry Vehicles", Tooltip="Forestry vehicles."),
	ACTOR_HAZARDOUS_GOODS_VEHICLES = 21			UMETA(DisplayName="Hazardous Goods Vehicles", Tooltip="Hazardous goods vehicles."),
	ACTOR_HORSE_CARRIAGES = 22					UMETA(DisplayName="Horse Carriages", Tooltip="Horse carriages."),
	ACTOR_HORSE_RIDERS = 23						UMETA(DisplayName="Horse Riders", Tooltip="Horse riders."),
	ACTOR_INLINE_SKATERS = 24					UMETA(DisplayName="Inline Skaters", Tooltip="Inline skaters."),
	ACTOR_MEDICAL_VEHICLES = 25					UMETA(DisplayName="Medical Vehicles", Tooltip="Medical vehicles."),
	ACTOR_MILITARY_VEHICLES = 26				UMETA(DisplayName="Military Vehicles", Tooltip="Military vehicles."),
	ACTOR_MOPEDS = 27							UMETA(DisplayName="Mopeds", Tooltip="Mopeds."),
	ACTOR_MOTORCYCLES = 28						UMETA(DisplayName="Motorcycles", Tooltip="Motorcycles."),
	ACTOR_MOTORIZED_MULTITRACK_VEHICLES = 29	UMETA(DisplayName="Motorized Multitrack Vehicles", Tooltip="Motorized multi-track vehicles."),
	ACTOR_OPERATIONAL_AND_UTILITY_VEHICLES = 30	UMETA(DisplayName="Operational and Utility Vehicles", Tooltip="Operational and utility vehicles."),
	ACTOR_PEDESTRIANS = 31						UMETA(DisplayName="Pedestrians", Tooltip="Pedestrians."),
	ACTOR_PUBLIC_TRANSPORT_VEHICLES = 32		UMETA(DisplayName="Public Transport Vehicles", Tooltip="Public transport vehicles."),
	ACTOR_RAILROAD_TRAFFIC = 33					UMETA(DisplayName="Railroad Traffic", Tooltip="Railroad traffic."),
	ACTOR_RESIDENTS = 34						UMETA(DisplayName="Residents", Tooltip="Residents. Note In the German StVO, typically denoted with the text \"Anlieger\" or \"Bewohner\""),
	ACTOR_SLURRY_TRANSPORT = 35					UMETA(DisplayName="Slurry Transport", Tooltip="Slurry transport."),
	ACTOR_TAXIS = 36							UMETA(DisplayName="Taxis", Tooltip="Taxis."),
	ACTOR_TRACTORS = 37							UMETA(DisplayName="Tractors", Tooltip="Tractors. Note In the German StVO, tractors are defined as motorized vehicles that are not allowed to, or cannot, drive faster than 25 km/h"),
	ACTOR_TRAILERS = 38							UMETA(DisplayName="Trailers", Tooltip="Trailers."),
	ACTOR_TRAMS = 39							UMETA(DisplayName="Trams", Tooltip="Trams."),
	ACTOR_TRUCKS = 40							UMETA(DisplayName="Trucks", Tooltip="Trucks. Note In the German StVO, trucks are defined as motorized vehicles that are heavier than 3.5 t"),
	ACTOR_TRUCKS_WITH_SEMITRAILERS = 41			UMETA(DisplayName="Trucks with Semi-Trailers", Tooltip="Trucks with semi-trailers."),
	ACTOR_TRUCKS_WITH_TRAILERS = 42				UMETA(DisplayName="Trucks with Trailers", Tooltip="Trucks with trailers."),
	ACTOR_VEHICLES_WITH_GREEN_BADGES = 43		UMETA(DisplayName="Vehicles with Green Badges", Tooltip="Vehicles with green badges."),
	ACTOR_VEHICLES_WITH_RED_BADGES = 44			UMETA(DisplayName="Vehicles with Red Badges", Tooltip="Vehicles with red badges."),
	ACTOR_VEHICLES_WITH_YELLOW_BADGES = 45		UMETA(DisplayName="Vehicles with Yellow Badges", Tooltip="Vehicles with yellow badges."),
	ACTOR_WATER_POLLUTANT_VEHICLES = 46			UMETA(DisplayName="Water Pollutant Vehicles", Tooltip="Water pollutant vehicles."),
	ACTOR_WINTER_SPORTSPEOPLE = 47				UMETA(DisplayName="Winter Sportspeople", Tooltip="Winter sportspeople.")
};

UENUM(BlueprintType)
enum class EArrowDirection : uint8
{
	DIRECTION_UNKNOWN = 0										UMETA(Hidden, DisplayName="Unknown", Tooltip="Direction of sign is unknown (must not be used in ground truth)."),
	DIRECTION_OTHER = 1											UMETA(DisplayName="Other", Tooltip="Other (specified but known) direction."),
	DIRECTION_NO_DIRECTION = 2									UMETA(DisplayName="No Direction", Tooltip="	No arrow direction is specified."),
	DIRECTION_DIRECT_0_DEG = 3									UMETA(DisplayName="Direct 0 DEG", Tooltip="An arrow pointing straight ahead in the direction of driving."),
	DIRECTION_DIRECT_45_DEG_RIGHT = 4							UMETA(DisplayName="Direct 45 DEG Right", Tooltip="A straight arrow pointing 45 degrees to the right in the direction of driving."),
	DIRECTION_DIRECT_45_DEG_LEFT = 5							UMETA(DisplayName="Direct 45 DEG Left", Tooltip="A straight arrow pointing 45 degrees to the left in the direction of driving."),
	DIRECTION_DIRECT_90_DEG_RIGHT = 6							UMETA(DisplayName="Direct 90 DEG Right", Tooltip="A straight arrow pointing 90 degrees to the right in the direction of driving."),
	DIRECTION_DIRECT_90_DEG_LEFT = 7							UMETA(DisplayName="Direct 90 DEG Left", Tooltip="A straight arrow pointing 90 degrees to the left in the direction of driving."),
	DIRECTION_DIRECT_135_DEG_RIGHT = 8							UMETA(DisplayName="Direct 135 DEG Right", Tooltip="A straight arrow pointing 135 degrees to the right in the direction of driving."),
	DIRECTION_DIRECT_135_DEG_LEFT = 9							UMETA(DisplayName="Direct 135 DEG Left", Tooltip="A straight arrow pointing 135 degrees to the left in the direction of driving."),
	DIRECTION_DIRECT_180_DEG = 10								UMETA(DisplayName="Direct 180 DEG", Tooltip="A straight arrow pointing oposite to the direction of driving."),
	DIRECTION_TURN_45_DEG_RIGHT = 11							UMETA(DisplayName="Turn 45 DEG Right", Tooltip="A curved arrow pointing 45 degrees to the right in the direction of driving."),
	DIRECTION_TURN_45_DEG_LEFT = 12								UMETA(DisplayName="Turn 45 DEG Left", Tooltip="A curved arrow pointing 45 degrees to the left in the direction of driving."),
	DIRECTION_TURN_90_DEG_RIGHT = 13							UMETA(DisplayName="Turn 90 DEG Right", Tooltip="A curved arrow pointing 90 degrees to the right in the direction of driving."),
	DIRECTION_TURN_90_DEG_LEFT = 14								UMETA(DisplayName="Turn 90 DEG Left", Tooltip="A curved arrow pointing 90 degrees to the left in the direction of driving."),
	DIRECTION_TURN_135_DEG_RIGHT = 15							UMETA(DisplayName="Turn 135 DEG Right", Tooltip="A curved arrow pointing 135 degrees to the right in the direction of driving."),
	DIRECTION_TURN_135_DEG_LEFT = 16							UMETA(DisplayName="Turn 135 DEG Left", Tooltip="A curved arrow pointing 135 degrees to the left in the direction of driving."),
	DIRECTION_TURN_180_DEG_RIGHT = 17							UMETA(DisplayName="Turn 180 DEG Right", Tooltip="A u-turn arrow towards the right."),
	DIRECTION_TURN_180_DEG_LEFT = 18							UMETA(DisplayName="Turn 180 DEG Left", Tooltip="A u-turn arrow towards the left."),
	DIRECTION_CIRCLE_0_DEG = 19									UMETA(DisplayName="Circle 0 DEG", Tooltip="An arrow that includes a fraction of a circle and points forward in the direction of driving. Used typically for roundabouts."),
	DIRECTION_CIRCLE_45_DEG_RIGHT = 20							UMETA(DisplayName="Circle 45 DEG Right", Tooltip="An arrow that includes a fraction of a circle and points in 45 degrees to the right in the direction of driving. Used typically for roundabouts."),
	DIRECTION_CIRCLE_45_DEG_LEFT = 21							UMETA(DisplayName="Circle 45 DEG Left", Tooltip="An arrow that includes a fraction of a circle and points in 45 degrees to the left in the direction of driving. Used typically for roundabouts."),
	DIRECTION_CIRCLE_90_DEG_RIGHT = 22							UMETA(DisplayName="Circle 90 DEG Right", Tooltip="An arrow that includes a fraction of a circle and points in 90 degrees to the right in the direction of driving. Used typically for roundabouts."),
	DIRECTION_CIRCLE_90_DEG_LEFT = 23							UMETA(DisplayName="Circle 90 DEG Left", Tooltip="An arrow that includes a fraction of a circle and points in 90 degrees to the left in the direction of driving. Used typically for roundabouts."),
	DIRECTION_CIRCLE_135_DEG_RIGHT = 24							UMETA(DisplayName="Circle 135 DEG Right", Tooltip="An arrow that includes a fraction of a circle and points in 135 degrees to the right in the direction of driving. Used typically for roundabouts."),
	DIRECTION_CIRCLE_135_DEG_LEFT = 25							UMETA(DisplayName="Circle 135 DEG Left", Tooltip="An arrow that includes a fraction of a circle and points in 135 degrees to the left in the direction of driving. Used typically for roundabouts."),
	DIRECTION_CIRCLE_180_DEG = 26								UMETA(DisplayName="Circle 180 DEG", Tooltip="An arrow that includes a fraction of a circle and points in the oposite to the direction of driving. Can be used in detours in roundabouts."),
	DIRECTION_KEEP_LEFT_TO_TURN_0_DEG = 27						UMETA(DisplayName="Keep Left to Turn 0 DEG", Tooltip="An arrow that includes a fraction of a square and points forward in direction of driving. Can be used for detours where you have to use a separate left lane to drive ahead."),
	DIRECTION_KEEP_RIGHT_TO_TURN_0_DEG = 28						UMETA(DisplayName="Keep Right to Turn 0 DEG", Tooltip="An arrow that includes a fraction of a square and points forward in direction of driving. Can be used for detours where you have to use a separate right lane to drive ahead."),
	DIRECTION_KEEP_LEFT_TO_TURN_90_DEG_RIGHT = 29				UMETA(DisplayName="Keep Left to Turn 90 DEG Right", Tooltip="An arrow that includes a fraction of a square and points in 90 degrees to the right in direction of driving. Can be used for detours where you have to use a separate left lane to turn right."),
	DIRECTION_KEEP_RIGHT_TO_TURN_90_DEG_LEFT = 30				UMETA(DisplayName="Keep Right to Turn 90 DEG Left", Tooltip="An arrow that includes a fraction of a square and points in 90 degrees to the right in direction of driving. Can be used for detours where you have to use a separate right lane to turn left."),
	DIRECTION_KEEP_LEFT_DRIVE_BACK_TO_TURN_90_DEG_RIGHT = 31	UMETA(DisplayName="Keep Left Drive Back to Turn 90 DEG Right", Tooltip="An arrow that includes a fraction of a square and points in 90 degrees to the right in direction of driving. Can be used for detours where you have to use a separate left lane and you have to drive back to turn right."),
	DIRECTION_KEEP_RIGHT_DRIVE_BACK_TO_TURN_90_DEG_LEFT = 32	UMETA(DisplayName="Keep Right Drive Back to Turn 90 DEG Left", Tooltip="An arrow that includes a fraction of a square and points in 90 degrees to the right in direction of driving. Can be used for detours where you have to use a separate right lane and you have to drive back to turn left.")
};